### ISSUE TITLE
Make <code> links more visible

### ISSUE THREAD

**Issue by richdougherty** [playframework/playframework.com#21]
When we link to API docs we often put a link around `<code>` styled text. These links are really hard to see. A normal link is coloured green, but a link around `<code>` has no additional styling. What I think we should do is apply a slightly different style to code that's within an anchor, e.g.

```css
a code {
  border-color: ...;
  text-color: ...;
  background-color: ...;
}

a:hover code {
  border-color: ...;
  text-color: ...;
  background-color: ...;
}
```
