### ISSUE TITLE
Tables in doc

### ISSUE THREAD

**Issue by cchantep** [playframework/playframework.com#3]
Seems styles for table inside page body can be improved for doc generated from markdown on playframework.com (e.g. type table at end of Anorm page).

```css
#content sup {
  font-size: x-small; 
  vertical-align:top }

#content table tr {
  background-color: #fff;
  border-top: 1px solid #ccc
}

#content table th, #content table td {
  border: 1px solid #ddd;
  padding: 6px 13px
}

#content table th { font-weight: bold }

#content table tr:nth-child(2n) { background-color: #f8f8f8 }
```
